######################################################################
# Automatically generated by qmake (3.0) Fri Nov 24 13:52:40 2017
######################################################################

QT       += core gui opengl

TEMPLATE = app
TARGET = min_OpenGL_Qt_1
INCLUDEPATH += .

# Input
HEADERS += gl_wgt_1.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += gl_wgt_1.cpp main.cpp mainwindow.cpp
