######################################################################
# Automatically generated by qmake (3.0) Sun Oct 29 14:44:08 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = lbl_tmr
INCLUDEPATH += .

# Input
HEADERS += Wdo.h
SOURCES += main.cpp Wdo.cpp
